name: Report a visual bug
description: The game has a visual or gameplay issue introduced by this patch
labels: ["visual bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Show and Tell"
      description: Optionally, let us know any further details on how to get to this screen.
      placeholder: Drag and drop to upload a screenshot showing the problem.
    validations:
      required: true

  - type: dropdown
    id: executable
    attributes:
      label: Executable
      description: Which executable did you use to start the game?
      options:
        - "Sims2.exe (Base game)"
        - "Sims2EP1.exe (University)"
        - "Sims2EP2.exe (Nightlife)"
        - "Sims2EP3.exe (Open For Business)"
        - "Sims2EP4.exe (Pets)"
        - "Sims2EP5.exe (Seasons)"
        - "Sims2EP6.exe (Bon Voyage)"
        - "Sims2EP7.exe (FreeTime)"
        - "Sims2EP8.exe (Apartment Life)"
        - "Sims2EP9.exe (Mansion and Garden Stuff)"
        - "Sims2EP9.exe (Ultimate Collection / Fun With Pets)"
        - "Sims2SP1.exe (Family Fun Stuff)"
        - "Sims2SP2.exe (Glamour Life Stuff)"
        - "Sims2SP4.exe (Celebration Stuff)"
        - "Sims2SP5.exe (H&M® Fashion Stuff)"
        - "Sims2SP6.exe (Teen Style Stuff)"
        - "Sims2SP7.exe (Kitchen & Bath Interior Design Stuff)"
        - "Sims2SP8.exe (IKEA® Home Stuff)"
    validations:
      required: true
