name: Test

on: [push, pull_request]

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.12'
            architecture: 'x64'

      - name: Cache Python Environment
        uses: actions/cache@v3
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Download Test File
        run: |
          wget https://github.com/lah7/sims2-4k-ui-patch/files/10831338/ui.package.zip
          mkdir -p tests/files/
          mv ui.package.zip tests/files/ui.package.xz
          xz -d tests/files/ui.package.xz

      - name: Run Unit Tests
        run: |
          source venv/bin/activate
          python3 -m unittest discover tests/ -v
